name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install AVR GCC
        run: sudo apt-get install -y binutils-avr gcc-avr avr-libc

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: "Unix Makefiles"
          options: >
            "CMAKE_TOOLCHAIN_FILE=./external/cmake-avr/generic-gcc-avr.cmake"
            "AVR_UPLOADTOOL_PORT=n/a"

      # - name: Build
      #   run: cmake --build build

      # - name: Run test suite
      #   run: ./build/tests

