name: build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install AVR GCC
        run: sudo apt-get install -y binutils-avr gcc-avr avr-libc

      - name: Install CMake
        run: sudo apt-get install cmake

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true

      - name: Generate
        run: cmake . -B build -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=./external/cmake-avr/generic-gcc-avr.cmake -DAVR_UPLOADTOOL_PORT=none

      - name: Build
        run: cmake --build build

