name: run_tests
on:
  push:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
            submodules: true

      - name: Setup CMake
        uses: threeal/cmake-action@v1.3.0

      - name: Build
        run: cmake --build build

      - name: Run test suite
        run: ./build/tests

